/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yangtt_personal_testjni_Java2CJNI */

#ifndef _Included_yangtt_personal_testjni_Java2CJNI
#define _Included_yangtt_personal_testjni_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yangtt_personal_testjni_Java2CJNI
 * Method:    java2c
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yangtt_personal_testjni_Java2CJNI_java2c
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
